name: hourly-taxi-demand-pipeline

on:
  schedule:
    - cron: '0 * * * *'  # Every hour at minute 0


jobs:
  feature_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'
      
      - name: Set up uv
        uses: actions/setup-uv@v1
        if:   steps.cache.outputs.cache-hit != 'true'

        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python workflow from bash script
        env:
          HOPSWORKS_API_KEY: ${{ secrets.HOPSWORKS_API_KEY }}
        run: uv run jupyter nbconvert --to notebook --execute \
          notebooks/12_feature_pipeline.ipynb
